error.LookupError: rename 'message' property to something else
At least some installs of Python 2.6+ complain with:

    mercurial/error.py:26: DeprecationWarning: BaseException.message has been
        deprecated as of Python 2.6

This patch renames the property away from 'message' so that Python no longer
complains.

--HG--
extra : rebase_source : e7785573a4af258101d0cc0b0947a6de65273096